version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  selenium:
    image: selenium/standalone-chrome:3.141.59-yttrium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"

  # test:
  #   image: django
  #   command: python manage.py test
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db