version: "3.3"
   
services:
  web:
    build: .
    command: 
      - /bin/bash
      - -c 
      - |
        mkdocs serve --dev-addr=0.0.0.0:8000
    restart: always 
    volumes:
      - .:/code
    ports:
      - "8000:8000"