name: DevSecOps

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # https://github.com/marketplace/actions/markdown-linting-action
    - name: Lint changelog file
      uses: avtodev/markdown-lint@v1
      with:
        # rules: 'src/docs/changelog.js'
        # config: '/lint/config/changelog.yml'
        args: './src/docs/*.md'

