name: DevSecOps

on:
  push:
    paths:
      - '**.md'

jobs:
  lint-changelog:
    name: Lint changelog markdowns
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog markdown
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        args: './src/docs/*.md'

    # Reference
    # https://github.com/marketplace/actions/markdown-linting-action
